[[main]]
none = "none"

[[main]]
name = "Achievements"
pre = "dribbble"
pageRef = "achievements"
identifier = "S9sndyP2Qs"
weight = 9_999

[[main]]
name = "Projects"
pre = "codepen"
pageRef = "projects"
identifier = "HIHWy4a6tQ"
weight = 9_999

[[main]]
name = "Resources"
pre = "rss-square"
pageRef = "resources"
identifier = "cZQ1TvKIzS"
weight = 9_999

[[footer]]
none = "none"
